<?php
/**
 * GroupsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Описание API для сервиса Wappi.pro
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * GroupsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GroupsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiSyncGroupAdminDemotePost
     *
     * Убрать права администратора группы для контакта.
     *
     */
    public function testApiSyncGroupAdminDemotePost()
    {
    }

    /**
     * Test case for apiSyncGroupAdminPromovePost
     *
     * Добавить права администратора группы контакту.
     *
     */
    public function testApiSyncGroupAdminPromovePost()
    {
    }

    /**
     * Test case for apiSyncGroupAdminsGetGet
     *
     * Получить список администраторов из группы.
     *
     */
    public function testApiSyncGroupAdminsGetGet()
    {
    }

    /**
     * Test case for apiSyncGroupCreatePost
     *
     * Создать новую группу.
     *
     */
    public function testApiSyncGroupCreatePost()
    {
    }

    /**
     * Test case for apiSyncGroupLeavePost
     *
     * Покинуть группу.
     *
     */
    public function testApiSyncGroupLeavePost()
    {
    }

    /**
     * Test case for apiSyncGroupParticipantAddPost
     *
     * Добавить контакт в группу.
     *
     */
    public function testApiSyncGroupParticipantAddPost()
    {
    }

    /**
     * Test case for apiSyncGroupParticipantRemovePost
     *
     * Удалить контакт из группы.
     *
     */
    public function testApiSyncGroupParticipantRemovePost()
    {
    }

    /**
     * Test case for apiSyncGroupParticipantsGetGet
     *
     * Получить контакты из группы.
     *
     */
    public function testApiSyncGroupParticipantsGetGet()
    {
    }
}
