<?php
/**
 * MessagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Описание API для сервиса Wappi.pro
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * MessagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiSyncMessageDeletePost
     *
     * Удалить сообщение.
     *
     */
    public function testApiSyncMessageDeletePost()
    {
    }

    /**
     * Test case for apiSyncMessageFileSendPost
     *
     * Отправить файл.
     *
     */
    public function testApiSyncMessageFileSendPost()
    {
    }

    /**
     * Test case for apiSyncMessageReplyPost
     *
     * Ответить на сообщение.
     *
     */
    public function testApiSyncMessageReplyPost()
    {
    }

    /**
     * Test case for apiSyncMessageSendPost
     *
     * Отправить сообщение.
     *
     */
    public function testApiSyncMessageSendPost()
    {
    }

    /**
     * Test case for apiSyncMessagesGetGet
     *
     * Получить сообщения.
     *
     */
    public function testApiSyncMessagesGetGet()
    {
    }

    /**
     * Test case for apiSyncMessagesUnreadGetGet
     *
     * Получить непрочитанные сообщения.
     *
     */
    public function testApiSyncMessagesUnreadGetGet()
    {
    }
}
